### ISSUE TITLE
Add type definitions

### ISSUE THREAD

**Issue by kkomelin** [kkomelin/isomorphic-dompurify#1]
DOMPurify public methods are defined here: https://github.com/cure53/DOMPurify/blob/master/src/purify.js

Examples of type definition files:
- https://github.com/developit/unfetch/blob/master/packages/isomorphic-unfetch/index.d.ts
- https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types

**Comment by NicholasEllul** [comment]
Thanks for making this! I went ahead and made changes to add typing based on the [existing DOMPurify types](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/dompurify) found in the DefinitelyTyped repo.  If you add me as a collaborator to this repo I can open up a pull request for you to review.

![screencast 2020-04-02 14-40-39](https://user-images.githubusercontent.com/15018469/78289616-701ad080-74f0-11ea-994e-07a94e2c397e.gif)

**Comment by kkomelin** [comment]
Hi @NicholasEllul, Thanks for that. I've added you to the collaborators, so please go ahead and send your PR.

**Comment by kkomelin** [comment]
Here we go https://github.com/kkomelin/isomorphic-dompurify/releases/tag/0.2.0

Thank you very much @NicholasEllul for your efforts!
