### ISSUE TITLE
Add information about the minimum node version

### ISSUE THREAD

**Issue by gaurav5430** [kkomelin/isomorphic-dompurify#129]
With jsdom 20, there is a minimum node version dependency which is specified in the jsdom package.json, but it seems the engines property is not taken into account for transitive dependencies and hence `npm i` does not fail on the consumer of isomorphic-dompurify, but at runtime it throws an error

Might make sense to mention this in the readme / troubleshooting somewhere

**Comment by kkomelin** [comment]
Thank you @gaurav5430 Yes, it makes sense. I will think about a better place to add this information.

**Comment by kkomelin** [comment]
@gaurav5430 Just added this information https://github.com/kkomelin/isomorphic-dompurify#requirements . Please review
