### ISSUE TITLE
Request body is being removed

### ISSUE THREAD

**Issue by mehuljain32** [kkomelin/isomorphic-dompurify#133]
I'm using version 0.20.0 and node.js version: v14.19.1 and restify version:8.5.1
When I'm using sanitized() method and passing request object inside it, only request headers are being kept everything else is being removed including request body of POST request. Is there any way to keep the request body? Or is it a bug?

**Comment by kkomelin** [comment]
Hi @mehuljain32 ,

> When I'm using sanitized() method and passing request object inside it,

The `sanitize()` function only accepts strings.
```javascript
DOMPurify.sanitize('only strings here, please')
```

Could you please provide the piece of code which you're debugging?

**Comment by mehuljain32** [comment]
Hi @kkomelin, 
Thanks for this, yeah understood. For strings it works fine.

**Comment by kkomelin** [comment]
@mehuljain32 You're welcome.
