### ISSUE TITLE
_isomorphicDompurify.default.sanitize is not a function error in jest environment

### ISSUE THREAD

**Issue by Daggron** [kkomelin/isomorphic-dompurify#141]
### Whats the problem.

I am using ismorphic-dompurify in my application which uses RTL and jest for tests setup. When I am trying to run the component's tests which uses `DOMPurify.sanitize` from the library the tests environment throws an error as shown in screen shot below.

<img width="1012" alt="Screenshot 2022-08-29 at 9 27 58 PM" src="https://user-images.githubusercontent.com/41940582/187243401-d5459c82-1710-4164-84df-8243af5f55d5.png">

Can you guys help me with this ?

Our package versions for notable libraries are as follows

"isomorphic-dompurify"  - 0.19.0 (because we need to support some applications which use node version equal to 12
 "jest" -  26.1.0,
"@testing-library/jest-dom": "^5.11.1",
"@testing-library/react": "^10.4.7",
"@testing-library/react-hooks": "^3.4.1",

**Comment by kkomelin** [comment]
Hi @Daggron ,
Thanks for reporting this issue. And sorry for not being able to react on it promptly.
Could you please a piece of code where you import the library? you `import` or `require` statement.
