### ISSUE TITLE
target blank get added to every url

### ISSUE THREAD

**Issue by tariqinaam** [kkomelin/isomorphic-dompurify#180]
Hi,
I am using this library in nextjs SSR environment.
No custom rule applied or anything. I am using`afterSanitizeAttributes` hook to add target attribute. however target=_blank get added to every available link with/without target attribute.

```DOMPurify.addHook("afterSanitizeAttributes", function (node) {
    // set all elements owning target to target=_blank
    if ("target" in node) {
      node.setAttribute("target", "_blank");
      node.setAttribute("rel", "noopener");
    }
  });
  const clean = DOMPurify.sanitize(content); 
  ```

 Do i need to configure anything else to selectively add target? thanks

**Comment by kkomelin** [comment]
Hi @tariqinaam,

Thanks for reporting this issue.

We're just an isomorphic wrapper around the [dompurify](https://github.com/cure53/DOMPurify) project, so it'd be better if you could report this issue to its issue quite https://github.com/cure53/DOMPurify/issues/new
