### ISSUE TITLE
Requirements for Node.js 14

### ISSUE THREAD

**Issue by JayDing** [kkomelin/isomorphic-dompurify#209]
Hi! I got an error when I exec `next build`

![image](https://github.com/kkomelin/isomorphic-dompurify/assets/6994536/e7d9383e-4d9d-4f5b-b5cb-80d6e3e000ef)

This is what I got when I install `1.8.0` version 

![image](https://github.com/kkomelin/isomorphic-dompurify/assets/6994536/9aeb11c8-5a23-4f53-9643-a0c08ba197be)

According to this,

<img width="1317" alt="image" src="https://github.com/kkomelin/isomorphic-dompurify/assets/6994536/4c072ce3-cb89-4c46-b065-467609268382">

I downgrade to `1.3.0`, and it worked!
so I thought the document should update for Node.js 14

<img width="448" alt="image" src="https://github.com/kkomelin/isomorphic-dompurify/assets/6994536/6f2eca48-3ec8-4b59-9273-935e86c680ab">

Dependencies:
- `node v14.21.3`
- `react 18.2.0`
- `next 12.3.4`
- `isomorphic-dompurify 1.8.0`

**Comment by kkomelin** [comment]
Thank you @JayDing . I've just updated the README accordingly. Please review https://github.com/kkomelin/isomorphic-dompurify#requirements
