### ISSUE TITLE
Isomorphic Dompurify Remix support ?

### ISSUE THREAD

**Issue by JeromeTrottier** [kkomelin/isomorphic-dompurify#214]
Hi! I'm trying to use `isomorphic-dompurify` to sanitize html in a remix application (more specifically hydrogen), but I keep having this error 
![Untitled-1](https://github.com/kkomelin/isomorphic-dompurify/assets/81482137/c689b844-53c9-41a0-9ea3-65cec3841705)

I could use the `dompurify` and sanitize on the client side, but would prefer if it would on the server too.

Has anyone looked into this?

**Comment by kkomelin** [comment]
Thanks @JeromeTrottier for reporting it here.

My guess is that it's more or less related to these issues https://github.com/kkomelin/isomorphic-dompurify/issues/203 https://github.com/kkomelin/isomorphic-dompurify/issues/54

**Comment by kkomelin** [comment]
According to the error description, I can say that Remix is trying to use the `browser` entry point from package.json on server, which is incorrect, so it should be fixed on their side.
