### ISSUE TITLE
usage import issue with vite named export 'sanitize' not found

### ISSUE THREAD

**Issue by isimmons** [kkomelin/isomorphic-dompurify#241]
I followed the usage example for import in a basic Astro project. Typescript is good with it and Astro seems good with it in dev mode until the page loads or refreshes. Then I get a 500 server error in devtools.

On the server side in the console I get
```
23:43:58 [ERROR] [vite] Named export 'sanitize' not found. The requested module 'isomorphic-dompurify' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'isomorphic-dompurify';
const {sanitize} = pkg;
``` 

As the hint in the terminal shows, if I do the following, it works
```js
import DOMPurify from 'isomorphic-dompurify';

// either this way
const { sanitize } = DOMPurify;
const clean = sanitize(dirtyHTML);

// or this way
const clean = DOMPurify.sanitize(dirtyHTML);
```

I didn't know if this is an issue with exports in the package or vite or just need a note under the usage section. But wanted to let you know.

**Comment by kkomelin** [comment]
You're right @isimmons . I've just recently simplified the Usage section of the Readme and removed importing the entire module but it might be necessary in the browser. Will improve the Readme now according to your findings.

**Comment by kkomelin** [comment]
@isimmons Tried to reflect your findings [here](https://github.com/kkomelin/isomorphic-dompurify/commit/0bd593d5808aa9e80f6f7e75cb9a02819a9f43ee). Please take a look and let me know what you think.

**Comment by isimmons** [comment]
@kkomelin Looks great to me. By the way, the package is working great in my use case. Thanks

**Comment by kkomelin** [comment]
@isimmons Thank you for your contribution!
