### ISSUE TITLE
Cannot find package on server with Nuxt 

### ISSUE THREAD

**Issue by Aniketsurya** [kkomelin/isomorphic-dompurify#258]
We are using nuxt 3 (ssr true) application. Trying to use this package, its working fine in local. But when we try to deploy it, it fails with this issue. 

[nuxt] [request error] [unhandled] [500] Cannot find package 'isomorphic-dompurify' imported from /home/site/wwwroot/server/chunks/app/server.mjs

We are using import statement as follows 

import DOMPurify from "isomorphic-dompurify";

Let me know if I need to also add some other dependency. I already added jsdom and Dompurify separately and tried deploying.

**Comment by kkomelin** [comment]
Hey @Aniketsurya ,
Thanks for reporting the issue.
Can you give me more information about your server environment?

**Comment by Aniketsurya** [comment]
I am using Azure app service to deploy and to run it with a startup command using pm2.
One more thing which I noticed is if I try to make it run on local with pm2 it runs well, but only that the same stage it fails in the pipeline. Seems like some import way is not correct. Or it is not compatible with Nuxt 3?

**Comment by kkomelin** [comment]
Hey @Aniketsurya ,
That's hard to debug for me because I don't have an Azure account.
As for the package not being compatible with Nuxt 3, if it's working locally, then it's compatible with Next 3. It might be not compatible with your specific Azure setup, however.

**Comment by Aniketsurya** [comment]
Hey @kkomelin, the difference between local and Azure environment is the OS. We run Azure on Linux, and local is on windows. Can that be a issue? If yes, what can be work around?

**Comment by kkomelin** [comment]
@Aniketsurya Linux is the default server OS. I'm using it myself locally. So I don't think Linux is the issue. 
What package manager are you using to build the project on the server? Can you share your deploy log?

**Comment by Aniketsurya** [comment]
Hey @kkomelin, I can't share the logs but the above was the main error shown. I am using npm for installing and pm2 for deployment and running the application but with pm2 it runs in local correctly.

**Comment by Aniketsurya** [comment]
Hey @kkomelin , I have been looking into this issue for quite a time now, got some different error currently so while building the project using nuxt build, it doesn't build the package properly for isomorphic-dompurify.

I build the package and zip it, while deploying I unzip it, while that unzipping it throws an error that 

ENOTDIR: not a directory 'node_modules/dompurify'

If I check that zip package by downloading manually it has "dompurify" as a folder (directory) itself. 
Do you have any ideas I can try?

**Comment by Aniketsurya** [comment]
The issue is solved using RunFromZip and changing the startup command location of index.mjs.

**Comment by ashraf-gemini** [comment]
@Aniketsurya @kkomelin Facing the same issue here

Here's the codesandbox link to reproduce https://codesandbox.io/p/devbox/with-ssr-uch9k


<img width="1723" alt="image" src="https://github.com/kkomelin/isomorphic-dompurify/assets/139562410/51a13530-b04b-41af-a8da-8b280b0d7013">

**Comment by mohdashraf010897** [comment]
@kkomelin Any updates here?

**Comment by kkomelin** [comment]
@ashraf-gemini The library you're using in the provided code example `@appbaseio/reactivesearch-vue` depends on a previous version of `isomorphic-dompurify` (^1.12.0). Please ask its developers to update `isomorphic-dompurify` to the latest.

**Comment by ashraf-gemini** [comment]
@kkomelin I am the maintainer of the package and I updated the version yesterday but still facing the same problem.

Here's the updated Codesandbox https://codesandbox.io/p/devbox/twilight-frost-qtwfxp

**Comment by kkomelin** [comment]
@ashraf-gemini Ah, I see. I've updated the package a few minutes ago. Current version is [2.12.0](https://www.npmjs.com/package/isomorphic-dompurify/v/2.12.0)

**Comment by kkomelin** [comment]
@mohdashraf010897 The package you included @appbaseio/reactivesearch-vue is [still using](https://github.com/appbaseio/reactivesearch/blob/57267e55388c204245737672660fd44bb4e79be0/packages/vue/package.json#L47) "isomorphic-dompurify": "^1.12.0" but we're on 2 now.

**Comment by ashraf-gemini** [comment]
@kkomelin It's just that the code changes aren't pushed post the version release, if you check the version within the shared codesandbox for appbase/reactivesearch-vue; it's 3.3.7-beta.2 which uses isomorphic-dompurify@2.x
