### ISSUE TITLE
NextJs Integration

### ISSUE THREAD

**Issue by Psykoxen** [kkomelin/isomorphic-dompurify#270]
Hi, i'm trying to use your lib in my own components library and then import it in Next.js. Everything works in my library but in the Next integration it causes some missing errors

```
Module not found: Can't resolve 'fs'  
Module not found: Can't resolve 'child_process'  
Module not found: Can't resolve 'net'  
Module not found: Can't resolve 'tls'  
Module not found: Can't resolve './xhr-sync-worker.js'
....
```

**Comment by kkomelin** [comment]
Hi @Psykoxen ,
Thanks for reporting.
Not sure it's related to the isomorphic-dompurify. Can you give a link to your library?
