### ISSUE TITLE
Property `setAttribute` does not exist on type `Node & Record<"target", unknown>`

### ISSUE THREAD

**Issue by prajwalkulkarni** [kkomelin/isomorphic-dompurify#299]
I've been using `isomorphic-dompurify` package for a few months now. But when I was trying to do a prod deployment yesterday the pipeline build failed with the error
> Property `setAttribute` does not exist on type `Node & Record<"target", unknown>`

Upon nuking and reinstalling `node_modules` and trying to build the application locally I encountered the same error. 
<img width="618" alt="Screenshot 2024-11-18 at 7 12 47 PM" src="https://github.com/user-attachments/assets/eefd43e4-fe4f-4f28-975f-c0ad63b7b344">
<img width="918" alt="Screenshot 2024-11-18 at 7 12 34 PM" src="https://github.com/user-attachments/assets/057c7f9a-3c68-4ab9-bb75-ea272b864d0f">

isomorphic-dompurify version: 2.15.0 (tried with the v2.16.0 as well which resulted in the same error)
Node version: 20.18.0

I'm unable to understand why this started happening suddenly when no changes related to the package were made.

**Comment by kkomelin** [comment]
Thanks for reporting @prajwalkulkarni! I've just removed the third-party types, so now Isomorphic Dompurify relies on the Dompurify native types. Please test with the new 2.17.0 version https://github.com/kkomelin/isomorphic-dompurify/releases/tag/v2.17.0

**Comment by prajwalkulkarni** [comment]
Thank you for the update. Will test with the latest version.
Additionally, I wanted to share a few observations:
1. The above error was fixed when I updated the `if` condition to:
`if(node instanceof Element && node.hasAttribute('target'))`

2. Alternatively, when I reverted the `package-lock.json` of my project without changing the version of the package or any `if` conditions, that fixed the issue as well. I'm particularly curious about what happened here.

Note: In both the cases I'm using `v2.15.0`

**Comment by kkomelin** [comment]
@prajwalkulkarni Thanks for sharing your observations but I don't think they are related to `isomorphic-dompurify` itself. It's just a tiny wrapper for `dompurify`.

Since you have found a solution for your problem, I'm closing this issue for now. Feel free to open another issue for the latest `isomorphic-dompurify` version if the problem occurs.
