### ISSUE TITLE
Set up Dependabot to track DOMPurify releases

### ISSUE THREAD

**Issue by NicholasEllul** [kkomelin/isomorphic-dompurify#4]
https://github.com/marketplace/dependabot-preview

Dependabot is a free tool that can be installed onto this repo which will automatically open pull requests when a dependency is out of date. Adding this integration will make it easy to keep up to date with DOMPurify updates.

**Comment by kkomelin** [comment]
@NicholasEllul Thanks a great idea. Thanks. I've just enabled Dependabot for this repo. Let me check if we need some additional configuration for the task.

**Comment by kkomelin** [comment]
@NicholasEllul I've added Dependabot config https://github.com/kkomelin/isomorphic-dompurify/blob/master/dependabot.yml Please review and let me know if you think there is anything else we can do for this repo.

**Comment by NicholasEllul** [comment]
Great work. When DOMPurify gets updated we can see if dependabot picks up the change and opens a PR. Since it looks like this issue is solved we can go ahead and close it.

**Comment by kkomelin** [comment]
Thanks @NicholasEllul. Yes, let's wait for a new DOMPurify release and see what happens.
