### ISSUE TITLE
Bumping to 0.16.0 - ReferenceError: TextEncoder is not defined

### ISSUE THREAD

**Issue by danpottshimself** [kkomelin/isomorphic-dompurify#91]
When installing - `"isomorphic-dompurify": "^0.16.0"` I get the following error within a jest test that previously passed. 

> Error: ReferenceError: TextEncoder is not defined

js file: 
```javascript
import DOMPurify from "isomorphic-dompurify";

return DOMPurify.sanitize(input.trim(), { ADD_ATTR: ["target"] });
```

Test: 
```javascript
import sanitize from "./sanitizeHtml";

describe("sanitize", () => {
    it("remove js from input", () => {
        expect(sanitize("<img onload='alert(1)' />")).toEqual("<img>");
    });
});
```

Any ideas what this may be? Thanks in advance

**Comment by kkomelin** [comment]
Hi @danpottshimself ,

Thanks for reporting the issue.

First of all, let's make sure that you don't have any dependency conflicts by removing `node_modules` folder and then installing all dependencies again the following way:
```bash
npm install
# or 
yarn
```

**Comment by kkomelin** [comment]
By the way, I reformatted the issue description a little bit.

**Comment by kkomelin** [comment]
I've just added [an additional automated test](https://github.com/kkomelin/isomorphic-dompurify/commit/eba1c03e964b618807d3d3e8106f6ddaf434de2f#diff-13876b4beb64b9f156474dc78f9c923952a7ca210d4507b6b3135bbe244f8a60R12) to cover your particular case and it [passed](https://app.travis-ci.com/github/kkomelin/isomorphic-dompurify/builds/240964776).

**Comment by danpottshimself** [comment]
@kkomelin odd, I guess this could be some form of clash between dependencies I have installed elsewhere. I have tried multiple node module cleans/rm's and re-installs to no avail. I guess the issue is my side so you can close this issue, thanks for the support

**Comment by cnorthwood** [comment]
I'm also getting this fwiw, so it is slightly broader. Not entirely sure what the conflict is, perhaps one of the dependencies here isn't tightly bound enough so something else is pinning it to an older version?

**Comment by danpottshimself** [comment]
That makes me feel less crazy @cnorthwood.  I was originally thinking it could be jsdom environment potentially since in version 16, it looks like jest etc have been bumped?

**Comment by cnorthwood** [comment]
ah yes - that would explain it, and why @kkomelin's automated test passed. Jest with JSDom polyfills that call by itself, so it'll work in a Jest environment because JSDom has polyfilled that function, but won't when not running under Jest.

**Comment by kkomelin** [comment]
Thanks guys. I will try to reproduce the issue without Jest. Will keep you updated.

**Comment by kkomelin** [comment]
Just tested through a Node.js script (Node 14.16):
```javascript
require('isomorphic-dompurify');
DOMPurify.setConfig({ALLOWED_TAGS: ['b']});
console.log(DOMPurify.sanitize('<b>dddd</b><iframe>Iframe!</iframe>'));
```
And it worked fine.

Could you please give me more details on what are your environments so I could try to reproduce the issue locally? Server/client? Next.js/React/others?

**Comment by kkomelin** [comment]
By the way, do you use Yarn or NPM for dependency management?

**Comment by cnorthwood** [comment]
I use Yarn - I've rolled back for now but will try and reproduce.

This is server-side Node 14 (Apollo Server) with TypeScript. I dont' use DOMPurify as a global like that, this is how I use it:
```
import { addHook, sanitize as _sanitize } from "isomorphic-dompurify";

// only let target="_blank" exist on A tags and enforce rel="noopener"
addHook("afterSanitizeAttributes", (node) => {
  if ("target" in node) {
    if (node.tagName === "A" && node.getAttribute("target") === "_blank") {
      node.setAttribute("rel", "noopener");
    } else {
      node.removeAttribute("target");
    }
  }
});

export const sanitize = (body: string) => _sanitize(body, { ADD_TAGS: ["iframe"], ADD_ATTR: ["target"] });
```

**Comment by kkomelin** [comment]
Thanks @cnorthwood Will try to play with your example.

Although I don't think it helps but I've just updated `jsdom` to the latest minor https://github.com/kkomelin/isomorphic-dompurify/commit/e466c367689d18aa675cbde3cb6c2f9acd95497b . If you want to test the updated dev snapshot, just install it like this `yarn add kkomelin/isomorphic-dompurify#master`

**Comment by cnorthwood** [comment]
sadly not. For more info, here's the full stack trace I get:

```
 FAIL  api/resolvers/Mutation/createArticle.test.ts
  ● Test suite failed to run

    ReferenceError: TextEncoder is not defined

      1 | import { ForbiddenError } from "apollo-server-errors";
    > 2 | import { addHook, sanitize as _sanitize } from "isomorphic-dompurify";
        | ^
      3 | import { Model } from "sequelize/types";
      4 |
      5 | import User from "../../db/models/User";

      at Object.<anonymous> (node_modules/whatwg-url/lib/encoding.js:2:21)
      at Object.<anonymous> (node_modules/whatwg-url/lib/url-state-machine.js:5:34)
      at Object.<anonymous> (node_modules/whatwg-url/lib/URL-impl.js:2:13)
      at Object.<anonymous> (node_modules/whatwg-url/lib/URL.js:442:14)
      at Object.<anonymous> (node_modules/whatwg-url/webidl2js-wrapper.js:3:13)
      at Object.<anonymous> (node_modules/whatwg-url/index.js:3:34)
      at Object.<anonymous> (node_modules/jsdom/lib/api.js:7:19)
      at node_modules/isomorphic-dompurify/index.js:1:278
      at Object.<anonymous> (node_modules/isomorphic-dompurify/index.js:1:344)
      at Object.<anonymous> (api/validators/index.ts:2:1)
      at Object.<anonymous> (db/models/Question.ts:4:1)
      at Object.<anonymous> (db/models/Answer.ts:13:1)
      at Object.<anonymous> (db/createTestAccounts.ts:3:1)
      at Object.<anonymous> (api/resolvers/Mutation/createArticle.test.ts:3:1)
      at TestScheduler.scheduleTests (node_modules/@jest/core/build/TestScheduler.js:333:13)
      at runJest (node_modules/@jest/core/build/runJest.js:401:19)
      at _run10000 (node_modules/@jest/core/build/cli/index.js:320:7)
      at runCLI (node_modules/@jest/core/build/cli/index.js:173:3)
```

**Comment by cnorthwood** [comment]
so the issue appears to be in whatwg-url

```
$ yarn why whatwg-url
yarn why v1.22.13
[1/4] 🤔  Why do we have the module "whatwg-url"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "whatwg-url@10.0.0"
info Has been hoisted to "whatwg-url"
info Reasons this module exists
   - Hoisted from "isomorphic-dompurify#jsdom#whatwg-url"
   - Hoisted from "isomorphic-dompurify#jsdom#data-urls#whatwg-url"
info Disk size without dependencies: "140KB"
info Disk size with unique dependencies: "412KB"
info Disk size with transitive dependencies: "460KB"
info Number of shared dependencies: 3
=> Found "node-fetch#whatwg-url@5.0.0"
info This module exists because "node-fetch" depends on it.
info Disk size without dependencies: "76KB"
info Disk size with unique dependencies: "348KB"
info Disk size with transitive dependencies: "396KB"
info Number of shared dependencies: 3
=> Found "jest-environment-jsdom#whatwg-url@8.7.0"
info Reasons this module exists
   - "jest-cli#jest-config#jest-environment-jsdom#jsdom" depends on it
   - Hoisted from "jest-cli#jest-config#jest-environment-jsdom#jsdom#whatwg-url"
   - Hoisted from "jest-cli#jest-config#jest-environment-jsdom#jsdom#data-urls#whatwg-url"
info Disk size without dependencies: "136KB"
info Disk size with unique dependencies: "5.28MB"
info Disk size with transitive dependencies: "5.32MB"
info Number of shared dependencies: 4
```

**Comment by kkomelin** [comment]
Just for reference https://github.com/jsdom/whatwg-url/issues/209

**Comment by cnorthwood** [comment]
Ah, so it's a version mismatch with Jest and that breaking it: https://stackoverflow.com/questions/57712235/referenceerror-textencoder-is-not-defined-when-running-react-scripts-test

**Comment by kkomelin** [comment]
Good catch @cnorthwood ! Now when we know the cause, what solution would you recommend?

**Comment by kkomelin** [comment]
Jsdom is a complex project which has already caused some dependency pain https://github.com/kkomelin/isomorphic-dompurify/issues/54

**Comment by maxgfr** [comment]
Hi, I had the same issue. 

To solve that, I move back to `dompurify` by doing something like that in my React component :

```tsx
import DOMPurify from "dompurify";
import React from "react";

import { htmlParser } from "../lib";

type Props = {
  children: string;
  inline?: boolean;
};

const Html = ({ children, inline = false, ...props }: Props): JSX.Element => {
  if (typeof window !== "undefined") {
    return(
      <div
        {...props}
        dangerouslySetInnerHTML={{
          __html: DOMPurify.sanitize(htmlParser(children)),
        }}
      />
    );
  }
  return <></>;
};

export default Html;
```

The downside is that the component is only available client side...

**Comment by tinykite** [comment]
For anyone hitting this same issue, I was able to fix this on a project by including the following in my `jest.setup.js` file: 

```
import { TextDecoder, TextEncoder } from 'util'

global.TextEncoder = TextEncoder
global.TextDecoder = TextDecoder
```

**Comment by aakashbacancy** [comment]
I installed and I'm facing a similar issue. 

```
The test suite failed to run

    ReferenceError: TextEncoder is not defined
```

What is the right solution? 

Node version: `14.7.0`

**Comment by dannyyu92** [comment]
I've tried 
```
import { TextDecoder, TextEncoder } from 'util'

global.TextEncoder = TextEncoder
global.TextDecoder = TextDecoder
```
in my jest setup

but I just get this error:

```
    TypeError: TextEncoder is not a constructor

    > 5 | import DOMPurify from 'isomorphic-dompurify';
    ```

any ideas?

**Comment by Vavaste** [comment]
I've tried each one of the solutions provided above but since i'm working with nextJest  the tests were failing.
I solved it by adding

` setupFiles: ["path/to/personalizedJest.setup.js"],`

to the personalized configuration for jest, in this file i just imported TextEncoder and TextDecoder from util:

```
import { TextDecoder, TextEncoder } from 'util';

global.TextEncoder = TextEncoder;
global.TextDecoder = TextDecoder;
```

**Comment by donald-boosted** [comment]
For me, I had to add the following to `jest.setup.js`

```
import { TextDecoder, TextEncoder } from 'util';

global.TextEncoder = TextEncoder;
global.TextDecoder = TextDecoder;
```

and import the lib like `import * as dompurify from 'isomorphic-dompurify';`

**Comment by stevedeighton** [comment]
For me, the TextDecoder had a type mismatch issue with the above approach, so I solved it with this syntax instead:

```
import { TextEncoder, TextDecoder } from 'util';

Object.assign(global, { TextDecoder, TextEncoder });
```

Thanks to leonheess - https://stackoverflow.com/questions/68468203/why-am-i-getting-textencoder-is-not-defined-in-jest

**Comment by kopach** [comment]
Not reproducible for me anymore in `2.13.0`
I guess, issue can be closed

**Comment by kkomelin** [comment]
@kopach Thanks for the update. Yes, it's a very old issue, so let's close it for now.
